name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint || true

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

    # Uncomment the following steps if you want to deploy to a specific platform
    # You'll need to add the appropriate secrets in your GitHub repository

    # - name: Deploy to Production
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   # Add your deployment steps here
    #   # For example, if deploying to Vercel:
    #   # uses: amondnet/vercel-action@v20
    #   # with:
    #   #   vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #   #   vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
    #   #   vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
